name:               "Bergrós Gígja Þorsteinsdóttir"
description:        "Portfolio"

accentcolor:        "#e01b5d"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

google_analytics:   UA-164668668-1

markdown:           kramdown

nav:
  - name:           "About"
    link:           "about"
    download:       false
  - name:           "CV"
    link:           "resume.pdf"
    download:       true

social:
  github:         "bergrosgigja"
  linkedin:       "bergrosgigja"
  instagram:      "bergrosgigja"

sass:
  style:            :compressed
  sass_dir:         _sass

plugins:
  - jemoji

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"